### PR TITLE
Update ljm_constants.json. Add last error registers.

### PR DESCRIPTION
**Pull request by sjarman28**
Added registers 55000 - 55003. These contain information about the last error code seen on the device.

### CODE REVIEW

**Review by Squibels — APPROVED** [review]
Looks good. Is there a better tag than CONFIG?

**Comment by sjarman28** [comment]
The only tags we currently have that I thought made sense were CONFIG and CORE. Should we make a new one, maybe something like LASTERR?

**Comment by Squibels** [comment]
CORE makes sense to me. It is part of the core functionality of the device and it's communication protocol.

**Comment by sjarman28** [comment]
Sounds good, I will update the tags to CORE and merge this branch back into master.

**Pull request merged**
